### ISSUE TITLE
Support app2app in android

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-sdk-android#160]
- [x] Support `App2AppOptions` in constructor (1)
- [x] Modify `finishAuthorization` to pass `x_app2app_device_key_jwt` during token exchange (2)
    - Generate and store device key in keystore
    - Only pass this parameter if `App2AppOptions` is not null
- [x] Modify `doRefreshAccessToken` to pass `x_app2app_device_key_jwt` during refresh (1)
    - Only pass this parameter if `App2AppOptions` is not null

- [x] Implement method `startApp2AppAuthentication(authorizationEndpoint: String, redirectURI: string)`
    - [x] Create intent to `authorizationEndpoint` using provided redirectURI and the configured clientID with proper code challenge (2)
    - [x] Fetch and parse `.well-known/assetlinks.json` using domain of `authorizationEndpoint` (2)
    - [x] Ensure the package name and signature matches the one in `.well-known/assetlinks.json` (2)
    - [x] Start the activity if all the above validation passed (1)

- [x] Implement method `handleApp2AppAuthenticationRequest(uri: Uri)`
    - [x] Parse `uri` to obtain `client_id` `redirect_uri` `code_challenge` (1)
    - [x] Fetch and parse `.well-known/assetlinks.json` using domain of `redirect_uri` (0.5)
    - [x] Ensure the package name and signature of app to handle the `redirect_uri` matches the one in `.well-known/assetlinks.json` (0.5)
    - [x] Call token endpoint using `grant_type=urn:authgear:params:oauth:grant-type:app2app` with proper jwt (1)
    - [x] Start an activity to pass `code` with `redirect_uri`
    - [x] Forward all errors in correct format

- [x] ~~Implement method `handleApp2AppAuthenticationResult(uri: Uri)`~~
- [x] Create a activity to handle result 
    - [x] Do all things we did in `finishAuthorization` (2)

- [x] Implement app2app in exmaple app (3)

- [x] Update spec to explain about removal of biometric prompt

**Comment by louischan-oursky** [comment]
One thing I want to note. The developer needs to handle the App Link in the application lifecycle method. How do they identify that the App Link is a app2app authentication URL? Is that our `handleApp2AppAuthenticationRequest` is no-op if the given Uri is not a app2app authentication URL?

**Comment by tung2744** [comment]
@louischan-oursky 

> The developer needs to handle the App Link in the application lifecycle method. How do they identify that the App Link is a app2app authentication URL?

They should know the app2app authentication url they are using, therefore it is possible to know it by checking the uri from the intent.

> Is that our handleApp2AppAuthenticationRequest is no-op if the given Uri is not a app2app authentication URL?

I think it should be an error.

**Comment by fungc-io** [comment]
delivered
