### ISSUE TITLE
[Demo app] Show all attributes in "Get UserInfo"

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-sdk-android#172]
All standard attributes and custom attributes should be shown

**Comment by randy1yu** [comment]
![Screenshot_20240520_152703](https://github.com/authgear/authgear-sdk-android/assets/19902333/53e858f0-9c2c-4a6b-a6f5-da990d5b4df0)

@fungc-io   It appears that this issue has already been resolved.
