### ISSUE TITLE
authorize should return response, not just state

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-sdk-android#24]

**Comment by roxk** [comment]
But js sdk only returns state @_@?

**Comment by louischan-oursky** [comment]
https://github.com/authgear/authgear-sdk-js/blob/master/packages/authgear-web/src/container.ts#L114

https://github.com/authgear/authgear-sdk-js/blob/master/packages/authgear-react-native/src/index.ts#L139
The type annotation is incorrect. The actual object being returned should be equivalent to Android's AuthorizeResult.
Let me open an issue to fix that.

**Comment by roxk** [comment]
Fixed in c6ce960.
