### ISSUE TITLE
Failed to install demo app from App Center on same devices 

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-sdk-android#81]
Failed to install the app on devices:
Nokia 8.1 (10), Google Pixel 3 (11)

Can install the app on devices:
Samsung C7 Pro (8.0), Nokia 7.2 (10)

There is error "App not installed" when the device failed to install the app. 

Error:
```
failed to install javasample-release.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package com.oursky.authgeartest]
```

refs:
https://github.com/microsoft/appcenter/issues/1738
https://github.com/microsoft/appcenter/issues/1990

**Comment by louischan-oursky** [comment]
Fixed by following this comment https://github.com/microsoft/appcenter/issues/1990#issuecomment-861053082
