### ISSUE TITLE
<input type="file"> is unresponsive in Android WebView

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-sdk-android#95]
Same problem as the RN SDK fixed here:
- https://github.com/authgear/authgear-sdk-js/issues/177
- https://github.com/authgear/authgear-sdk-js/pull/178

**Comment by fungc-io** [comment]
@louischan-oursky 
is this issue done by
https://github.com/authgear/authgear-sdk-android/commit/9dc62a6a1de2c17fb1a1759115d411ea608cb670 ?

**Comment by louischan-oursky** [comment]
Yes
